language: c
dist: xenial
sudo: false
matrix:
  include:
    - os: linux
      env: TARGET=linux64
    - os: linux
      env: TARGET=linux32 PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig
    # note: cross-build for win32 on osx as xenial's mingw-w64 compiler is too old to build working Qt apps,
    # see https://forum.qt.io/topic/87793/qt-5-10-mingw64-static-building-failed
    - os: osx
      env: TARGET=win32
    - os: osx
      env: TARGET=macos
env:
  global:
    - QTDIR=${TRAVIS_BUILD_DIR}/qt
    - QTPKG=qt-everywhere-src-5.12.0
    - QTURL="http://qt.mirror.constant.com/official_releases/qt/5.12/5.12.0/single/${QTPKG}.tar.xz"
cache:
  timeout: 1000
  directories:
    - ${QTDIR}
addons:
  artifacts:
    paths:
      - $(find . -maxdepth 1 -name 'hairless-midiserial*.zip' -o -name 'hairless-midiserial*.tgz' | tr "\n" ":")
    target_paths:
    - /travis_builds
  homebrew:
    packages:
      - mingw-w64
  apt:
    packages:
      - gettext
      - gcc-multilib
      - g++-multilib
      - fontconfig
      - libsm-dev
      - libasound2-dev
      - libudev-dev
      - libgraphite2-dev
      - libjpeg8-dev
      - libpng16-dev
      - libxcb1-dev
      - libice-dev
      - libicu-dev
      - zlib1g-dev
      - libbz2-dev
      - libfontconfig1-dev
      - libharfbuzz-dev
      - libpcre2-dev
      - libexpat1-dev
      - libxau-dev
      - libxdmcp-dev
      - uuid-dev
      - libasound2-dev:i386
      - libudev-dev:i386
      - libgraphite2-dev:i386
      - libjpeg8-dev:i386
      - libpng16-dev:i386
      - libxcb1-dev:i386
      - libice-dev:i386
      - libicu-dev:i386
      - zlib1g-dev:i386
      - libbz2-dev:i386
      - libsm-dev:i386
      - libfontconfig1-dev:i386
      - libharfbuzz-dev:i386
      - libstdc++6-4.7-dev:i386
      - libxrender-dev:i386
      - libxext-dev:i386
      - libpcre2-dev:i386
      - libexpat1-dev:i386
      - libxau-dev:i386
      - libxdmcp-dev:i386
      - uuid-dev:i386
before_install:
  - test -x ${QTDIR}/bin/qmake || ci_build/build_qt_static.sh
script:
  - cd ${TRAVIS_BUILD_DIR}
  - ${QTDIR}/bin/qmake
  - make
  - ./ci_build/package_hairless.sh

